/**
 * AI Generation Service — real API calls to Gemini (text) and Pollinations (images).
 * No mocks, no simulated delays.
 */

const GEMINI_API_KEY = 'AIzaSyC_vn5ZZ-agv7dNrArJRYr_3TtrcYSoz8w';
const GEMINI_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}`;

export type AITextResult = { ok: true; text: string } | { ok: false; error: string };

export type AIImageResult = { ok: true; imageUrl: string } | { ok: false; error: string };

/**
 * Generate text content using Google Gemini 1.5 Flash.
 * Takes a user prompt and returns the generated text.
 */
export async function generateTextWithGemini(prompt: string): Promise<AITextResult> {
    try {
        if (!prompt.trim()) {
            return { ok: false, error: 'Prompt cannot be empty' };
        }

        const response = await fetch(GEMINI_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                contents: [{
                    parts: [{ text: prompt }]
                }]
            })
        });

        if (!response.ok) {
            const errData = await response.json().catch(() => ({}));
            return { ok: false, error: errData?.error?.message || `Gemini API error: ${response.status}` };
        }

        const data = await response.json();
        const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!text) {
            return { ok: false, error: 'No text generated by Gemini' };
        }

        return { ok: true, text };
    } catch (err) {
        return { ok: false, error: err instanceof Error ? err.message : 'Network error' };
    }
}

/**
 * Generate an image URL using Pollinations AI.
 * Returns a direct URL that renders the AI-generated image (no API key needed).
 */
export function generateImageUrl(prompt: string): AIImageResult {
    if (!prompt.trim()) {
        return { ok: false, error: 'Prompt cannot be empty' };
    }
    const encoded = encodeURIComponent(prompt.trim());
    const imageUrl = `https://image.pollinations.ai/prompt/${encoded}`;
    return { ok: true, imageUrl };
}
