import {
    FileText, Heart, Star, Bookmark, Calendar, Clock,
    Target, Zap, Lightbulb, Rocket, Flag, Trophy,
    Coffee, Music, Camera, Book, Briefcase, Code,
    Palette, Sparkles, Sun, Moon, Cloud, Umbrella,
    Gift, Home, Mail, Phone, Settings, User,
    CheckCircle, AlertCircle, Info, XCircle, HelpCircle,
    TrendingUp, Activity, BarChart, PieChart, Database,
    Folder, File, Image, Video,
    type LucideIcon
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
    FileText,
    Heart,
    Star,
    Bookmark,
    Calendar,
    Clock,
    Target,
    Zap,
    Lightbulb,
    Rocket,
    Flag,
    Trophy,
    Coffee,
    Music,
    Camera,
    Book,
    Briefcase,
    Code,
    Palette,
    Sparkles,
    Sun,
    Moon,
    Cloud,
    Umbrella,
    Gift,
    Home,
    Mail,
    Phone,
    Settings,
    User,
    CheckCircle,
    AlertCircle,
    Info,
    XCircle,
    HelpCircle,
    TrendingUp,
    Activity,
    BarChart,
    PieChart,
    Database,
    Folder,
    File,
    Image,
    Video,
};

export const defaultIconName = 'FileText';
