// AUTO-GENERATED — do not edit by hand.
// Browsable listing for the picker: every icon with its Solar category.
// Solar Bold Duotone by 480 Design, licensed CC BY 4.0.
// https://creativecommons.org/licenses/by/4.0/

export interface SolarEntry {
    /** Solar icon id, e.g. "home-smile". */
    name: string;
    /** Human-readable label used for display and search. */
    label: string;
    /** Solar's own category, used to group the picker grid. */
    category: string;
}

const SOLAR_CATALOG: SolarEntry[] = [
    { name: "accessibility", label: "Accessibility", category: "UI" },
    { name: "add-circle", label: "Add circle", category: "UI" },
    { name: "add-folder", label: "Add folder", category: "Folders" },
    { name: "add-square", label: "Add square", category: "UI" },
    { name: "adhesive-plaster", label: "Adhesive plaster", category: "Medicine" },
    { name: "adhesive-plaster-2", label: "Adhesive plaster 2", category: "Medicine" },
    { name: "airbuds", label: "Airbuds", category: "Devices" },
    { name: "airbuds-case", label: "Airbuds case", category: "Devices" },
    { name: "airbuds-case-charge", label: "Airbuds case charge", category: "Devices" },
    { name: "airbuds-case-minimalistic", label: "Airbuds case minimalistic", category: "Devices" },
    { name: "airbuds-case-open", label: "Airbuds case open", category: "Devices" },
    { name: "airbuds-charge", label: "Airbuds charge", category: "Devices" },
    { name: "airbuds-check", label: "Airbuds check", category: "Devices" },
    { name: "airbuds-left", label: "Airbuds left", category: "Devices" },
    { name: "airbuds-remove", label: "Airbuds remove", category: "Devices" },
    { name: "airbuds-right", label: "Airbuds right", category: "Devices" },
    { name: "alarm", label: "Alarm", category: "Time" },
    { name: "alarm-add", label: "Alarm add", category: "Time" },
    { name: "alarm-pause", label: "Alarm pause", category: "Time" },
    { name: "alarm-play", label: "Alarm play", category: "Time" },
    { name: "alarm-remove", label: "Alarm remove", category: "Time" },
    { name: "alarm-sleep", label: "Alarm sleep", category: "Time" },
    { name: "alarm-turn-off", label: "Alarm turn off", category: "Time" },
    { name: "album", label: "Album", category: "Video" },
    { name: "align-bottom", label: "Align bottom", category: "Tools" },
    { name: "align-horizontal-center", label: "Align horizontal center", category: "Tools" },
    { name: "align-horizontal-spacing", label: "Align horizontal spacing", category: "Tools" },
    { name: "align-left", label: "Align left", category: "Tools" },
    { name: "align-right", label: "Align right", category: "Tools" },
    { name: "align-top", label: "Align top", category: "Tools" },
    { name: "align-vertical-center", label: "Align vertical center", category: "Tools" },
    { name: "align-vertical-spacing", label: "Align vertical spacing", category: "Tools" },
    { name: "alt-arrow-down", label: "Alt arrow down", category: "Arrows" },
    { name: "alt-arrow-left", label: "Alt arrow left", category: "Arrows" },
    { name: "alt-arrow-right", label: "Alt arrow right", category: "Arrows" },
    { name: "alt-arrow-up", label: "Alt arrow up", category: "Arrows" },
    { name: "archive", label: "Archive", category: "Notes" },
    { name: "archive-check", label: "Archive check", category: "Notes" },
    { name: "archive-down", label: "Archive down", category: "Notes" },
    { name: "archive-down-minimalistic", label: "Archive down minimalistic", category: "Notes" },
    { name: "archive-minimalistic", label: "Archive minimalistic", category: "Notes" },
    { name: "archive-up", label: "Archive up", category: "Notes" },
    { name: "archive-up-minimalistic", label: "Archive up minimalistic", category: "Notes" },
    { name: "armchair", label: "Armchair", category: "Home" },
    { name: "armchair-2", label: "Armchair 2", category: "Home" },
    { name: "arrow-down", label: "Arrow down", category: "Arrows" },
    { name: "arrow-left", label: "Arrow left", category: "Arrows" },
    { name: "arrow-left-down", label: "Arrow left down", category: "Arrows" },
    { name: "arrow-left-up", label: "Arrow left up", category: "Arrows" },
    { name: "arrow-right", label: "Arrow right", category: "Arrows" },
    { name: "arrow-right-down", label: "Arrow right down", category: "Arrows" },
    { name: "arrow-right-up", label: "Arrow right up", category: "Arrows" },
    { name: "arrow-to-down-left", label: "Arrow to down left", category: "Arrows Action" },
    { name: "arrow-to-down-right", label: "Arrow to down right", category: "Arrows Action" },
    { name: "arrow-to-top-left", label: "Arrow to top left", category: "Arrows Action" },
    { name: "arrow-to-top-right", label: "Arrow to top right", category: "Arrows Action" },
    { name: "arrow-up", label: "Arrow up", category: "Arrows" },
    { name: "asteroid", label: "Asteroid", category: "Astronomy" },
    { name: "atom", label: "Atom", category: "Astronomy" },
    { name: "augmented-reality", label: "Augmented reality", category: "UI" },
    { name: "backpack", label: "Backpack", category: "School" },
    { name: "backspace", label: "Backspace", category: "Text Formatting" },
    { name: "bacteria", label: "Bacteria", category: "Medicine" },
    { name: "bag", label: "Bag", category: "Shopping" },
    { name: "bag-2", label: "Bag 2", category: "Shopping" },
    { name: "bag-3", label: "Bag 3", category: "Shopping" },
    { name: "bag-4", label: "Bag 4", category: "Shopping" },
    { name: "bag-5", label: "Bag 5", category: "Shopping" },
    { name: "bag-check", label: "Bag check", category: "Shopping" },
    { name: "bag-cross", label: "Bag cross", category: "Shopping" },
    { name: "bag-heart", label: "Bag heart", category: "Shopping" },
    { name: "bag-music", label: "Bag music", category: "Shopping" },
    { name: "bag-music-2", label: "Bag music 2", category: "Shopping" },
    { name: "bag-smile", label: "Bag smile", category: "Shopping" },
    { name: "balloon", label: "Balloon", category: "UI" },
    { name: "balls", label: "Balls", category: "Sports" },
    { name: "banknote", label: "Banknote", category: "Money" },
    { name: "banknote-2", label: "Banknote 2", category: "Money" },
    { name: "bar-chair", label: "Bar chair", category: "Home" },
    { name: "basketball", label: "Basketball", category: "Sports" },
    { name: "bath", label: "Bath", category: "Home" },
    { name: "battery-charge", label: "Battery charge", category: "UI" },
    { name: "battery-charge-minimalistic", label: "Battery charge minimalistic", category: "UI" },
    { name: "battery-full", label: "Battery full", category: "UI" },
    { name: "battery-full-minimalistic", label: "Battery full minimalistic", category: "UI" },
    { name: "battery-half", label: "Battery half", category: "UI" },
    { name: "battery-half-minimalistic", label: "Battery half minimalistic", category: "UI" },
    { name: "battery-low", label: "Battery low", category: "UI" },
    { name: "battery-low-minimalistic", label: "Battery low minimalistic", category: "UI" },
    { name: "bed", label: "Bed", category: "Home" },
    { name: "bedside-table", label: "Bedside table", category: "Home" },
    { name: "bedside-table-2", label: "Bedside table 2", category: "Home" },
    { name: "bedside-table-3", label: "Bedside table 3", category: "Home" },
    { name: "bedside-table-4", label: "Bedside table 4", category: "Home" },
    { name: "bell", label: "Bell", category: "Notifications" },
    { name: "bell-off", label: "Bell off", category: "Notifications" },
    { name: "bell-ring", label: "Bell ring", category: "Notifications" },
    { name: "benzene-ring", label: "Benzene ring", category: "Medicine" },
    { name: "bicycling", label: "Bicycling", category: "Sports" },
    { name: "bicycling-round", label: "Bicycling round", category: "Sports" },
    { name: "bill", label: "Bill", category: "Money" },
    { name: "bill-2", label: "Bill 2", category: "List" },
    { name: "bill-check", label: "Bill check", category: "Money" },
    { name: "bill-cross", label: "Bill cross", category: "Money" },
    { name: "bill-list", label: "Bill list", category: "Money" },
    { name: "black-hole", label: "Black hole", category: "Astronomy" },
    { name: "black-hole-2", label: "Black hole 2", category: "Astronomy" },
    { name: "black-hole-3", label: "Black hole 3", category: "Astronomy" },
    { name: "bluetooth", label: "Bluetooth", category: "Devices" },
    { name: "bluetooth-circle", label: "Bluetooth circle", category: "Devices" },
    { name: "bluetooth-square", label: "Bluetooth square", category: "Devices" },
    { name: "bluetooth-wave", label: "Bluetooth wave", category: "Devices" },
    { name: "body", label: "Body", category: "UI" },
    { name: "body-shape", label: "Body shape", category: "Sports" },
    { name: "body-shape-minimalistic", label: "Body shape minimalistic", category: "Sports" },
    { name: "bolt", label: "Bolt", category: "UI" },
    { name: "bolt-circle", label: "Bolt circle", category: "UI" },
    { name: "bomb", label: "Bomb", category: "Security" },
    { name: "bomb-emoji", label: "Bomb emoji", category: "Security" },
    { name: "bomb-minimalistic", label: "Bomb minimalistic", category: "Security" },
    { name: "bone", label: "Bone", category: "Medicine" },
    { name: "bone-crack", label: "Bone crack", category: "Medicine" },
    { name: "bone-fracture", label: "Bone fracture", category: "Medicine" },
    { name: "bones", label: "Bones", category: "Medicine" },
    { name: "bonfire", label: "Bonfire", category: "Nature" },
    { name: "book", label: "Book", category: "School" },
    { name: "book-2", label: "Book 2", category: "School" },
    { name: "book-bookmark", label: "Book bookmark", category: "School" },
    { name: "book-bookmark-minimalistic", label: "Book bookmark minimalistic", category: "School" },
    { name: "book-minimalistic", label: "Book minimalistic", category: "School" },
    { name: "bookmark", label: "Bookmark", category: "School" },
    { name: "bookmark-circle", label: "Bookmark circle", category: "School" },
    { name: "bookmark-opened", label: "Bookmark opened", category: "School" },
    { name: "bookmark-square", label: "Bookmark square", category: "School" },
    { name: "bookmark-square-minimalistic", label: "Bookmark square minimalistic", category: "School" },
    { name: "boombox", label: "Boombox", category: "Devices" },
    { name: "bottle", label: "Bottle", category: "Food" },
    { name: "bowling", label: "Bowling", category: "Sports" },
    { name: "box", label: "Box", category: "UI" },
    { name: "box-minimalistic", label: "Box minimalistic", category: "UI" },
    { name: "branching-paths-down", label: "Branching paths down", category: "Map" },
    { name: "branching-paths-up", label: "Branching paths up", category: "Map" },
    { name: "broom", label: "Broom", category: "UI" },
    { name: "bug", label: "Bug", category: "IT" },
    { name: "bug-minimalistic", label: "Bug minimalistic", category: "IT" },
    { name: "buildings", label: "Buildings", category: "Building" },
    { name: "buildings-2", label: "Buildings 2", category: "Building" },
    { name: "buildings-3", label: "Buildings 3", category: "Building" },
    { name: "bus", label: "Bus", category: "Parts" },
    { name: "calculator", label: "Calculator", category: "School" },
    { name: "calculator-minimalistic", label: "Calculator minimalistic", category: "School" },
    { name: "calendar", label: "Calendar", category: "Time" },
    { name: "calendar-add", label: "Calendar add", category: "Time" },
    { name: "calendar-date", label: "Calendar date", category: "Time" },
    { name: "calendar-mark", label: "Calendar mark", category: "Time" },
    { name: "calendar-minimalistic", label: "Calendar minimalistic", category: "Time" },
    { name: "calendar-search", label: "Calendar search", category: "Time" },
    { name: "call-cancel", label: "Call cancel", category: "Call" },
    { name: "call-cancel-rounded", label: "Call cancel rounded", category: "Call" },
    { name: "call-chat", label: "Call chat", category: "Call" },
    { name: "call-chat-rounded", label: "Call chat rounded", category: "Call" },
    { name: "call-dropped", label: "Call dropped", category: "Call" },
    { name: "call-dropped-rounded", label: "Call dropped rounded", category: "Call" },
    { name: "call-medicine", label: "Call medicine", category: "Call" },
    { name: "call-medicine-rounded", label: "Call medicine rounded", category: "Call" },
    { name: "camera", label: "Camera", category: "Video" },
    { name: "camera-add", label: "Camera add", category: "Video" },
    { name: "camera-minimalistic", label: "Camera minimalistic", category: "Video" },
    { name: "camera-rotate", label: "Camera rotate", category: "Video" },
    { name: "camera-square", label: "Camera square", category: "Video" },
    { name: "car-battery", label: "Car battery", category: "Parts" },
    { name: "card", label: "Card", category: "Money" },
    { name: "card-2", label: "Card 2", category: "Money" },
    { name: "card-receive", label: "Card receive", category: "Money" },
    { name: "card-search", label: "Card search", category: "Money" },
    { name: "card-send", label: "Card send", category: "Money" },
    { name: "card-transfer", label: "Card transfer", category: "Money" },
    { name: "cardholder", label: "Cardholder", category: "Money" },
    { name: "cart", label: "Cart", category: "Shopping" },
    { name: "cart-2", label: "Cart 2", category: "Shopping" },
    { name: "cart-3", label: "Cart 3", category: "Shopping" },
    { name: "cart-4", label: "Cart 4", category: "Shopping" },
    { name: "cart-5", label: "Cart 5", category: "Shopping" },
    { name: "cart-check", label: "Cart check", category: "Shopping" },
    { name: "cart-cross", label: "Cart cross", category: "Shopping" },
    { name: "cart-large", label: "Cart large", category: "Shopping" },
    { name: "cart-large-2", label: "Cart large 2", category: "Shopping" },
    { name: "cart-large-3", label: "Cart large 3", category: "Shopping" },
    { name: "cart-large-4", label: "Cart large 4", category: "Shopping" },
    { name: "cart-large-minimalistic", label: "Cart large minimalistic", category: "Shopping" },
    { name: "cart-plus", label: "Cart plus", category: "Shopping" },
    { name: "case", label: "Case", category: "School" },
    { name: "case-minimalistic", label: "Case minimalistic", category: "School" },
    { name: "case-round", label: "Case round", category: "School" },
    { name: "case-round-minimalistic", label: "Case round minimalistic", category: "School" },
    { name: "cash-out", label: "Cash out", category: "Money" },
    { name: "cassette", label: "Cassette", category: "Devices" },
    { name: "cassette-2", label: "Cassette 2", category: "Devices" },
    { name: "cat", label: "Cat", category: "UI" },
    { name: "chair", label: "Chair", category: "Home" },
    { name: "chair-2", label: "Chair 2", category: "Home" },
    { name: "chandelier", label: "Chandelier", category: "Home" },
    { name: "chart", label: "Chart", category: "Business" },
    { name: "chart-2", label: "Chart 2", category: "Business" },
    { name: "chart-square", label: "Chart square", category: "Business" },
    { name: "chat-dots", label: "Chat dots", category: "Messages" },
    { name: "chat-line", label: "Chat line", category: "Messages" },
    { name: "chat-round", label: "Chat round", category: "Messages" },
    { name: "chat-round-call", label: "Chat round call", category: "Messages" },
    { name: "chat-round-check", label: "Chat round check", category: "Messages" },
    { name: "chat-round-dots", label: "Chat round dots", category: "Messages" },
    { name: "chat-round-like", label: "Chat round like", category: "Messages" },
    { name: "chat-round-line", label: "Chat round line", category: "Messages" },
    { name: "chat-round-money", label: "Chat round money", category: "Messages" },
    { name: "chat-round-unread", label: "Chat round unread", category: "Messages" },
    { name: "chat-round-video", label: "Chat round video", category: "Messages" },
    { name: "chat-square", label: "Chat square", category: "Messages" },
    { name: "chat-square-2", label: "Chat square 2", category: "Business" },
    { name: "chat-square-arrow", label: "Chat square arrow", category: "Messages" },
    { name: "chat-square-call", label: "Chat square call", category: "Messages" },
    { name: "chat-square-check", label: "Chat square check", category: "Messages" },
    { name: "chat-square-code", label: "Chat square code", category: "Messages" },
    { name: "chat-square-like", label: "Chat square like", category: "Messages" },
    { name: "chat-unread", label: "Chat unread", category: "Messages" },
    { name: "check-circle", label: "Check circle", category: "UI" },
    { name: "check-read", label: "Check read", category: "Messages" },
    { name: "check-square", label: "Check square", category: "UI" },
    { name: "checklist", label: "Checklist", category: "List" },
    { name: "checklist-minimalistic", label: "Checklist minimalistic", category: "List" },
    { name: "chef-hat", label: "Chef hat", category: "Food" },
    { name: "chef-hat-heart", label: "Chef hat heart", category: "Food" },
    { name: "chef-hat-minimalistic", label: "Chef hat minimalistic", category: "Food" },
    { name: "circle-bottom-down", label: "Circle bottom down", category: "Arrows Action" },
    { name: "circle-bottom-up", label: "Circle bottom up", category: "Arrows Action" },
    { name: "circle-top-down", label: "Circle top down", category: "Arrows Action" },
    { name: "circle-top-up", label: "Circle top up", category: "Arrows Action" },
    { name: "city", label: "City", category: "Building" },
    { name: "clapperboard", label: "Clapperboard", category: "Video" },
    { name: "clapperboard-edit", label: "Clapperboard edit", category: "Video" },
    { name: "clapperboard-open", label: "Clapperboard open", category: "Video" },
    { name: "clapperboard-open-play", label: "Clapperboard open play", category: "Video" },
    { name: "clapperboard-play", label: "Clapperboard play", category: "Video" },
    { name: "clapperboard-text", label: "Clapperboard text", category: "Video" },
    { name: "clipboard", label: "Clipboard", category: "Notes" },
    { name: "clipboard-add", label: "Clipboard add", category: "Notes" },
    { name: "clipboard-check", label: "Clipboard check", category: "Notes" },
    { name: "clipboard-heart", label: "Clipboard heart", category: "Notes" },
    { name: "clipboard-list", label: "Clipboard list", category: "Notes" },
    { name: "clipboard-remove", label: "Clipboard remove", category: "Notes" },
    { name: "clipboard-text", label: "Clipboard text", category: "Notes" },
    { name: "clock-circle", label: "Clock circle", category: "Time" },
    { name: "clock-square", label: "Clock square", category: "Time" },
    { name: "close-circle", label: "Close circle", category: "UI" },
    { name: "close-square", label: "Close square", category: "UI" },
    { name: "closet", label: "Closet", category: "Home" },
    { name: "closet-2", label: "Closet 2", category: "Home" },
    { name: "cloud", label: "Cloud", category: "Weather" },
    { name: "cloud-bolt", label: "Cloud bolt", category: "Weather" },
    { name: "cloud-bolt-minimalistic", label: "Cloud bolt minimalistic", category: "Weather" },
    { name: "cloud-check", label: "Cloud check", category: "Weather" },
    { name: "cloud-cross", label: "Cloud cross", category: "Weather" },
    { name: "cloud-download", label: "Cloud download", category: "Weather" },
    { name: "cloud-file", label: "Cloud file", category: "Files" },
    { name: "cloud-minus", label: "Cloud minus", category: "Weather" },
    { name: "cloud-plus", label: "Cloud plus", category: "Weather" },
    { name: "cloud-rain", label: "Cloud rain", category: "Weather" },
    { name: "cloud-snowfall", label: "Cloud snowfall", category: "Weather" },
    { name: "cloud-snowfall-minimalistic", label: "Cloud snowfall minimalistic", category: "Weather" },
    { name: "cloud-storage", label: "Cloud storage", category: "Devices" },
    { name: "cloud-storm", label: "Cloud storm", category: "Weather" },
    { name: "cloud-sun", label: "Cloud sun", category: "Weather" },
    { name: "cloud-sun-2", label: "Cloud sun 2", category: "Weather" },
    { name: "cloud-upload", label: "Cloud upload", category: "Weather" },
    { name: "cloud-waterdrop", label: "Cloud waterdrop", category: "Weather" },
    { name: "cloud-waterdrops", label: "Cloud waterdrops", category: "Weather" },
    { name: "clouds", label: "Clouds", category: "Weather" },
    { name: "cloudy-moon", label: "Cloudy moon", category: "Weather" },
    { name: "code", label: "Code", category: "IT" },
    { name: "code-2", label: "Code 2", category: "IT" },
    { name: "code-circle", label: "Code circle", category: "IT" },
    { name: "code-file", label: "Code file", category: "Files" },
    { name: "code-scan", label: "Code scan", category: "Security" },
    { name: "code-square", label: "Code square", category: "IT" },
    { name: "colour-tuning", label: "Colour tuning", category: "Tools" },
    { name: "command", label: "Command", category: "IT" },
    { name: "compass", label: "Compass", category: "Map" },
    { name: "compass-big", label: "Compass big", category: "Map" },
    { name: "compass-square", label: "Compass square", category: "Map" },
    { name: "conditioner", label: "Conditioner", category: "Home" },
    { name: "conditioner-2", label: "Conditioner 2", category: "Home" },
    { name: "confetti", label: "Confetti", category: "UI" },
    { name: "confetti-minimalistic", label: "Confetti minimalistic", category: "UI" },
    { name: "confounded-circle", label: "Confounded circle", category: "Faces" },
    { name: "confounded-square", label: "Confounded square", category: "Faces" },
    { name: "copy", label: "Copy", category: "UI" },
    { name: "copyright", label: "Copyright", category: "UI" },
    { name: "corkscrew", label: "Corkscrew", category: "Food" },
    { name: "cosmetic", label: "Cosmetic", category: "UI" },
    { name: "course-down", label: "Course down", category: "Business" },
    { name: "course-up", label: "Course up", category: "Business" },
    { name: "cpu", label: "Cpu", category: "Devices" },
    { name: "cpu-bolt", label: "Cpu bolt", category: "Devices" },
    { name: "creative-commons", label: "Creative commons", category: "UI" },
    { name: "crop", label: "Crop", category: "Tools" },
    { name: "crop-minimalistic", label: "Crop minimalistic", category: "Tools" },
    { name: "crown", label: "Crown", category: "UI" },
    { name: "crown-line", label: "Crown line", category: "UI" },
    { name: "crown-minimalistic", label: "Crown minimalistic", category: "UI" },
    { name: "crown-star", label: "Crown star", category: "UI" },
    { name: "cup", label: "Cup", category: "UI" },
    { name: "cup-first", label: "Cup first", category: "UI" },
    { name: "cup-hot", label: "Cup hot", category: "Food" },
    { name: "cup-music", label: "Cup music", category: "UI" },
    { name: "cup-paper", label: "Cup paper", category: "Food" },
    { name: "cup-star", label: "Cup star", category: "UI" },
    { name: "cursor", label: "Cursor", category: "UI" },
    { name: "cursor-square", label: "Cursor square", category: "UI" },
    { name: "danger", label: "Danger", category: "UI" },
    { name: "danger-circle", label: "Danger circle", category: "UI" },
    { name: "danger-square", label: "Danger square", category: "UI" },
    { name: "danger-triangle", label: "Danger triangle", category: "UI" },
    { name: "database", label: "Database", category: "UI" },
    { name: "delivery", label: "Delivery", category: "UI" },
    { name: "devices", label: "Devices", category: "Devices" },
    { name: "diagram-down", label: "Diagram down", category: "Business" },
    { name: "diagram-up", label: "Diagram up", category: "Business" },
    { name: "dialog", label: "Dialog", category: "Messages" },
    { name: "dialog-2", label: "Dialog 2", category: "Messages" },
    { name: "diploma", label: "Diploma", category: "School" },
    { name: "diploma-verified", label: "Diploma verified", category: "School" },
    { name: "diskette", label: "Diskette", category: "Devices" },
    { name: "dislike", label: "Dislike", category: "Like" },
    { name: "display", label: "Display", category: "Devices" },
    { name: "dna", label: "Dna", category: "Medicine" },
    { name: "document", label: "Document", category: "Notes" },
    { name: "document-2", label: "Document 2", category: "School" },
    { name: "document-add", label: "Document add", category: "Notes" },
    { name: "document-medicine", label: "Document medicine", category: "Notes" },
    { name: "document-text", label: "Document text", category: "Notes" },
    { name: "documents", label: "Documents", category: "Notes" },
    { name: "documents-minimalistic", label: "Documents minimalistic", category: "Notes" },
    { name: "dollar", label: "Dollar", category: "Money" },
    { name: "dollar-minimalistic", label: "Dollar minimalistic", category: "Money" },
    { name: "donut", label: "Donut", category: "Food" },
    { name: "donut-bitten", label: "Donut bitten", category: "Food" },
    { name: "double-alt-arrow-down", label: "Double alt arrow down", category: "Arrows" },
    { name: "double-alt-arrow-left", label: "Double alt arrow left", category: "Arrows" },
    { name: "double-alt-arrow-right", label: "Double alt arrow right", category: "Arrows" },
    { name: "double-alt-arrow-up", label: "Double alt arrow up", category: "Arrows" },
    { name: "download", label: "Download", category: "Arrows Action" },
    { name: "download-minimalistic", label: "Download minimalistic", category: "Arrows Action" },
    { name: "download-square", label: "Download square", category: "Arrows Action" },
    { name: "download-twice-square", label: "Download twice square", category: "Arrows Action" },
    { name: "dropper", label: "Dropper", category: "Medicine" },
    { name: "dropper-2", label: "Dropper 2", category: "Medicine" },
    { name: "dropper-3", label: "Dropper 3", category: "Medicine" },
    { name: "dropper-minimalistic", label: "Dropper minimalistic", category: "Medicine" },
    { name: "dropper-minimalistic-2", label: "Dropper minimalistic 2", category: "Medicine" },
    { name: "dumbbell", label: "Dumbbell", category: "Sports" },
    { name: "dumbbell-large", label: "Dumbbell large", category: "Sports" },
    { name: "dumbbell-large-minimalistic", label: "Dumbbell large minimalistic", category: "Sports" },
    { name: "dumbbell-small", label: "Dumbbell small", category: "Sports" },
    { name: "dumbbells", label: "Dumbbells", category: "Sports" },
    { name: "dumbbells-2", label: "Dumbbells 2", category: "Sports" },
    { name: "earth", label: "Earth", category: "Astronomy" },
    { name: "electric-refueling", label: "Electric refueling", category: "Parts" },
    { name: "emoji-funny-circle", label: "Emoji funny circle", category: "Faces" },
    { name: "emoji-funny-square", label: "Emoji funny square", category: "Faces" },
    { name: "end-call", label: "End call", category: "Call" },
    { name: "end-call-rounded", label: "End call rounded", category: "Call" },
    { name: "eraser", label: "Eraser", category: "Text Formatting" },
    { name: "eraser-circle", label: "Eraser circle", category: "Text Formatting" },
    { name: "eraser-square", label: "Eraser square", category: "Text Formatting" },
    { name: "euro", label: "Euro", category: "Money" },
    { name: "exit", label: "Exit", category: "Arrows Action" },
    { name: "explicit", label: "Explicit", category: "UI" },
    { name: "export", label: "Export", category: "Arrows Action" },
    { name: "expressionless-circle", label: "Expressionless circle", category: "Faces" },
    { name: "expressionless-square", label: "Expressionless square", category: "Faces" },
    { name: "eye", label: "Eye", category: "Security" },
    { name: "eye-closed", label: "Eye closed", category: "Security" },
    { name: "eye-scan", label: "Eye scan", category: "Security" },
    { name: "face-scan-circle", label: "Face scan circle", category: "Faces" },
    { name: "face-scan-square", label: "Face scan square", category: "Faces" },
    { name: "facemask-circle", label: "Facemask circle", category: "Faces" },
    { name: "facemask-square", label: "Facemask square", category: "Faces" },
    { name: "feed", label: "Feed", category: "UI" },
    { name: "ferris-wheel", label: "Ferris wheel", category: "UI" },
    { name: "figma", label: "Figma", category: "UI" },
    { name: "figma-file", label: "Figma file", category: "Files" },
    { name: "file", label: "File", category: "Files" },
    { name: "file-check", label: "File check", category: "Files" },
    { name: "file-corrupted", label: "File corrupted", category: "Files" },
    { name: "file-download", label: "File download", category: "Files" },
    { name: "file-favorite", label: "File favorite", category: "Files" },
    { name: "file-left", label: "File left", category: "Files" },
    { name: "file-remove", label: "File remove", category: "Files" },
    { name: "file-right", label: "File right", category: "Files" },
    { name: "file-send", label: "File send", category: "Files" },
    { name: "file-smile", label: "File smile", category: "Files" },
    { name: "file-text", label: "File text", category: "Files" },
    { name: "filter", label: "Filter", category: "UI" },
    { name: "filters", label: "Filters", category: "Tools" },
    { name: "fire", label: "Fire", category: "Nature" },
    { name: "fire-minimalistic", label: "Fire minimalistic", category: "Nature" },
    { name: "fire-square", label: "Fire square", category: "Nature" },
    { name: "flag", label: "Flag", category: "UI" },
    { name: "flag-2", label: "Flag 2", category: "UI" },
    { name: "flame", label: "Flame", category: "Nature" },
    { name: "flash-drive", label: "Flash drive", category: "Devices" },
    { name: "flashlight", label: "Flashlight", category: "UI" },
    { name: "flashlight-on", label: "Flashlight on", category: "UI" },
    { name: "flip-horizontal", label: "Flip horizontal", category: "Tools" },
    { name: "flip-vertical", label: "Flip vertical", category: "Tools" },
    { name: "floor-lamp", label: "Floor lamp", category: "Home" },
    { name: "floor-lamp-minimalistic", label: "Floor lamp minimalistic", category: "Home" },
    { name: "fog", label: "Fog", category: "Weather" },
    { name: "folder", label: "Folder", category: "Folders" },
    { name: "folder-2", label: "Folder 2", category: "Folders" },
    { name: "folder-check", label: "Folder check", category: "Folders" },
    { name: "folder-cloud", label: "Folder cloud", category: "Folders" },
    { name: "folder-error", label: "Folder error", category: "Folders" },
    { name: "folder-favorite-bookmark", label: "Folder favorite bookmark", category: "Folders" },
    { name: "folder-favorite-star", label: "Folder favorite star", category: "Folders" },
    { name: "folder-open", label: "Folder open", category: "Folders" },
    { name: "folder-path-connect", label: "Folder path connect", category: "Folders" },
    { name: "folder-security", label: "Folder security", category: "Folders" },
    { name: "folder-with-files", label: "Folder with files", category: "Folders" },
    { name: "football", label: "Football", category: "Sports" },
    { name: "forbidden", label: "Forbidden", category: "UI" },
    { name: "forbidden-circle", label: "Forbidden circle", category: "UI" },
    { name: "forward", label: "Forward", category: "Arrows Action" },
    { name: "forward-2", label: "Forward 2", category: "Arrows Action" },
    { name: "forward-right", label: "Forward right", category: "Messages" },
    { name: "four-k", label: "Four k", category: "UI" },
    { name: "fridge", label: "Fridge", category: "Home" },
    { name: "fuel", label: "Fuel", category: "UI" },
    { name: "full-screen", label: "Full screen", category: "Video" },
    { name: "full-screen-circle", label: "Full screen circle", category: "Video" },
    { name: "full-screen-square", label: "Full screen square", category: "Video" },
    { name: "gallery", label: "Gallery", category: "Video" },
    { name: "gallery-add", label: "Gallery add", category: "Video" },
    { name: "gallery-check", label: "Gallery check", category: "Video" },
    { name: "gallery-circle", label: "Gallery circle", category: "Video" },
    { name: "gallery-download", label: "Gallery download", category: "Video" },
    { name: "gallery-edit", label: "Gallery edit", category: "Video" },
    { name: "gallery-favorite", label: "Gallery favorite", category: "Video" },
    { name: "gallery-minimalistic", label: "Gallery minimalistic", category: "Video" },
    { name: "gallery-remove", label: "Gallery remove", category: "Video" },
    { name: "gallery-round", label: "Gallery round", category: "Video" },
    { name: "gallery-send", label: "Gallery send", category: "Video" },
    { name: "gallery-wide", label: "Gallery wide", category: "Video" },
    { name: "gameboy", label: "Gameboy", category: "Devices" },
    { name: "gamepad", label: "Gamepad", category: "Devices" },
    { name: "gamepad-charge", label: "Gamepad charge", category: "Devices" },
    { name: "gamepad-minimalistic", label: "Gamepad minimalistic", category: "Devices" },
    { name: "gamepad-no-charge", label: "Gamepad no charge", category: "Devices" },
    { name: "gamepad-old", label: "Gamepad old", category: "Devices" },
    { name: "garage", label: "Garage", category: "Building" },
    { name: "gas-station", label: "Gas station", category: "Parts" },
    { name: "ghost", label: "Ghost", category: "UI" },
    { name: "ghost-smile", label: "Ghost smile", category: "UI" },
    { name: "gift", label: "Gift", category: "UI" },
    { name: "glasses", label: "Glasses", category: "UI" },
    { name: "global", label: "Global", category: "Map" },
    { name: "globe", label: "Globe", category: "Map" },
    { name: "golf", label: "Golf", category: "Sports" },
    { name: "gps", label: "Gps", category: "Map" },
    { name: "graph", label: "Graph", category: "Business" },
    { name: "graph-down", label: "Graph down", category: "Business" },
    { name: "graph-down-new", label: "Graph down new", category: "Business" },
    { name: "graph-new", label: "Graph new", category: "Business" },
    { name: "graph-new-up", label: "Graph new up", category: "Business" },
    { name: "graph-up", label: "Graph up", category: "Business" },
    { name: "hamburger-menu", label: "Hamburger menu", category: "UI" },
    { name: "hand-heart", label: "Hand heart", category: "Hands" },
    { name: "hand-money", label: "Hand money", category: "Hands" },
    { name: "hand-pills", label: "Hand pills", category: "Hands" },
    { name: "hand-shake", label: "Hand shake", category: "Hands" },
    { name: "hand-stars", label: "Hand stars", category: "Hands" },
    { name: "hanger", label: "Hanger", category: "UI" },
    { name: "hanger-2", label: "Hanger 2", category: "UI" },
    { name: "hashtag", label: "Hashtag", category: "IT" },
    { name: "hashtag-chat", label: "Hashtag chat", category: "IT" },
    { name: "hashtag-circle", label: "Hashtag circle", category: "IT" },
    { name: "hashtag-square", label: "Hashtag square", category: "IT" },
    { name: "headphones-round", label: "Headphones round", category: "Devices" },
    { name: "headphones-round-sound", label: "Headphones round sound", category: "Devices" },
    { name: "headphones-square", label: "Headphones square", category: "Devices" },
    { name: "headphones-square-sound", label: "Headphones square sound", category: "Devices" },
    { name: "health", label: "Health", category: "Medicine" },
    { name: "heart", label: "Heart", category: "Like" },
    { name: "heart-angle", label: "Heart angle", category: "Like" },
    { name: "heart-crack", label: "Heart crack", category: "Like" },
    { name: "heart-lock", label: "Heart lock", category: "Like" },
    { name: "heart-pulse", label: "Heart pulse", category: "Medicine" },
    { name: "heart-pulse-2", label: "Heart pulse 2", category: "Medicine" },
    { name: "heart-shine", label: "Heart shine", category: "Like" },
    { name: "heart-unlock", label: "Heart unlock", category: "Like" },
    { name: "hearts", label: "Hearts", category: "Like" },
    { name: "help", label: "Help", category: "UI" },
    { name: "high-definition", label: "High definition", category: "UI" },
    { name: "high-quality", label: "High quality", category: "UI" },
    { name: "hiking", label: "Hiking", category: "Sports" },
    { name: "hiking-minimalistic", label: "Hiking minimalistic", category: "Sports" },
    { name: "hiking-round", label: "Hiking round", category: "Sports" },
    { name: "history", label: "History", category: "Time" },
    { name: "history-2", label: "History 2", category: "Time" },
    { name: "history-3", label: "History 3", category: "Time" },
    { name: "home", label: "Home", category: "UI" },
    { name: "home-2", label: "Home 2", category: "UI" },
    { name: "home-add", label: "Home add", category: "UI" },
    { name: "home-add-angle", label: "Home add angle", category: "UI" },
    { name: "home-angle", label: "Home angle", category: "UI" },
    { name: "home-angle-2", label: "Home angle 2", category: "UI" },
    { name: "home-smile", label: "Home smile", category: "UI" },
    { name: "home-smile-angle", label: "Home smile angle", category: "UI" },
    { name: "home-wi-fi", label: "Home wi fi", category: "UI" },
    { name: "home-wi-fi-angle", label: "Home wi fi angle", category: "UI" },
    { name: "hospital", label: "Hospital", category: "Building" },
    { name: "hourglass", label: "Hourglass", category: "Time" },
    { name: "hourglass-line", label: "Hourglass line", category: "Time" },
    { name: "house", label: "House", category: "Building" },
    { name: "i-phone", label: "I phone", category: "Devices" },
    { name: "import", label: "Import", category: "Arrows Action" },
    { name: "inbox", label: "Inbox", category: "Messages" },
    { name: "inbox-archive", label: "Inbox archive", category: "Messages" },
    { name: "inbox-in", label: "Inbox in", category: "Messages" },
    { name: "inbox-line", label: "Inbox line", category: "Messages" },
    { name: "inbox-out", label: "Inbox out", category: "Messages" },
    { name: "inbox-unread", label: "Inbox unread", category: "Messages" },
    { name: "incognito", label: "Incognito", category: "Security" },
    { name: "incoming-call", label: "Incoming call", category: "Call" },
    { name: "incoming-call-rounded", label: "Incoming call rounded", category: "Call" },
    { name: "infinite", label: "Infinite", category: "Astronomy" },
    { name: "info-circle", label: "Info circle", category: "UI" },
    { name: "info-square", label: "Info square", category: "UI" },
    { name: "jar-of-pills", label: "Jar of pills", category: "Medicine" },
    { name: "jar-of-pills-2", label: "Jar of pills 2", category: "Medicine" },
    { name: "key", label: "Key", category: "Security" },
    { name: "key-minimalistic", label: "Key minimalistic", category: "Security" },
    { name: "key-minimalistic-2", label: "Key minimalistic 2", category: "Security" },
    { name: "key-minimalistic-square", label: "Key minimalistic square", category: "Security" },
    { name: "key-minimalistic-square-2", label: "Key minimalistic square 2", category: "Security" },
    { name: "key-minimalistic-square-3", label: "Key minimalistic square 3", category: "Security" },
    { name: "key-square", label: "Key square", category: "Security" },
    { name: "key-square-2", label: "Key square 2", category: "Security" },
    { name: "keyboard", label: "Keyboard", category: "Devices" },
    { name: "kick-scooter", label: "Kick scooter", category: "Parts" },
    { name: "ladle", label: "Ladle", category: "Food" },
    { name: "lamp", label: "Lamp", category: "Home" },
    { name: "laptop", label: "Laptop", category: "Devices" },
    { name: "laptop-2", label: "Laptop 2", category: "Devices" },
    { name: "laptop-3", label: "Laptop 3", category: "Devices" },
    { name: "laptop-minimalistic", label: "Laptop minimalistic", category: "Devices" },
    { name: "layers", label: "Layers", category: "Tools" },
    { name: "layers-minimalistic", label: "Layers minimalistic", category: "Tools" },
    { name: "leaf", label: "Leaf", category: "Nature" },
    { name: "letter", label: "Letter", category: "Messages" },
    { name: "letter-opened", label: "Letter opened", category: "Messages" },
    { name: "letter-unread", label: "Letter unread", category: "Messages" },
    { name: "library", label: "Library", category: "Video" },
    { name: "lightbulb", label: "Lightbulb", category: "Devices" },
    { name: "lightbulb-bolt", label: "Lightbulb bolt", category: "Devices" },
    { name: "lightbulb-minimalistic", label: "Lightbulb minimalistic", category: "Devices" },
    { name: "lightning", label: "Lightning", category: "Devices" },
    { name: "like", label: "Like", category: "Like" },
    { name: "link", label: "Link", category: "Text Formatting" },
    { name: "link-circle", label: "Link circle", category: "Text Formatting" },
    { name: "link-minimalistic", label: "Link minimalistic", category: "Text Formatting" },
    { name: "link-minimalistic-2", label: "Link minimalistic 2", category: "Text Formatting" },
    { name: "link-round", label: "Link round", category: "Text Formatting" },
    { name: "link-round-angle", label: "Link round angle", category: "Text Formatting" },
    { name: "link-square", label: "Link square", category: "Text Formatting" },
    { name: "list", label: "List", category: "List" },
    { name: "list-arrow-down", label: "List arrow down", category: "List" },
    { name: "list-arrow-down-minimalistic", label: "List arrow down minimalistic", category: "List" },
    { name: "list-arrow-up", label: "List arrow up", category: "List" },
    { name: "list-arrow-up-minimalistic", label: "List arrow up minimalistic", category: "List" },
    { name: "list-check", label: "List check", category: "List" },
    { name: "list-check-minimalistic", label: "List check minimalistic", category: "List" },
    { name: "list-cross", label: "List cross", category: "List" },
    { name: "list-cross-minimalistic", label: "List cross minimalistic", category: "List" },
    { name: "list-down", label: "List down", category: "List" },
    { name: "list-down-minimalistic", label: "List down minimalistic", category: "List" },
    { name: "list-heart", label: "List heart", category: "List" },
    { name: "list-heart-minimalistic", label: "List heart minimalistic", category: "List" },
    { name: "list-up", label: "List up", category: "List" },
    { name: "list-up-minimalistic", label: "List up minimalistic", category: "List" },
    { name: "list-vertical", label: "List vertical", category: "List" },
    { name: "lock", label: "Lock", category: "Security" },
    { name: "lock-keyhole", label: "Lock keyhole", category: "Security" },
    { name: "lock-keyhole-minimalistic", label: "Lock keyhole minimalistic", category: "Security" },
    { name: "lock-keyhole-minimalistic-unlocked", label: "Lock keyhole minimalistic unlocked", category: "Security" },
    { name: "lock-keyhole-unlocked", label: "Lock keyhole unlocked", category: "Security" },
    { name: "lock-password", label: "Lock password", category: "Security" },
    { name: "lock-password-unlocked", label: "Lock password unlocked", category: "Security" },
    { name: "lock-unlocked", label: "Lock unlocked", category: "Security" },
    { name: "login", label: "Login", category: "Arrows Action" },
    { name: "login-2", label: "Login 2", category: "Arrows Action" },
    { name: "login-3", label: "Login 3", category: "Arrows Action" },
    { name: "logout", label: "Logout", category: "Arrows Action" },
    { name: "logout-2", label: "Logout 2", category: "Arrows Action" },
    { name: "logout-3", label: "Logout 3", category: "Arrows Action" },
    { name: "magic-wand", label: "Magic wand", category: "UI" },
    { name: "magic-wand-2", label: "Magic wand 2", category: "UI" },
    { name: "magic-wand-3", label: "Magic wand 3", category: "UI" },
    { name: "magnet", label: "Magnet", category: "UI" },
    { name: "magnet-wave", label: "Magnet wave", category: "UI" },
    { name: "magnifier", label: "Magnifier", category: "Search" },
    { name: "magnifier-bug", label: "Magnifier bug", category: "Search" },
    { name: "magnifier-zoom-in", label: "Magnifier zoom in", category: "Search" },
    { name: "magnifier-zoom-out", label: "Magnifier zoom out", category: "Search" },
    { name: "mailbox", label: "Mailbox", category: "Messages" },
    { name: "map", label: "Map", category: "Map" },
    { name: "map-arrow-down", label: "Map arrow down", category: "Map" },
    { name: "map-arrow-left", label: "Map arrow left", category: "Map" },
    { name: "map-arrow-right", label: "Map arrow right", category: "Map" },
    { name: "map-arrow-square", label: "Map arrow square", category: "Map" },
    { name: "map-arrow-up", label: "Map arrow up", category: "Map" },
    { name: "map-point", label: "Map point", category: "Map" },
    { name: "map-point-add", label: "Map point add", category: "Map" },
    { name: "map-point-favorite", label: "Map point favorite", category: "Map" },
    { name: "map-point-hospital", label: "Map point hospital", category: "Map" },
    { name: "map-point-remove", label: "Map point remove", category: "Map" },
    { name: "map-point-rotate", label: "Map point rotate", category: "Map" },
    { name: "map-point-school", label: "Map point school", category: "Map" },
    { name: "map-point-search", label: "Map point search", category: "Map" },
    { name: "map-point-wave", label: "Map point wave", category: "Map" },
    { name: "mask-happy", label: "Mask happy", category: "UI" },
    { name: "mask-sad", label: "Mask sad", category: "UI" },
    { name: "masks", label: "Masks", category: "UI" },
    { name: "maximize", label: "Maximize", category: "Arrows Action" },
    { name: "maximize-square", label: "Maximize square", category: "Arrows Action" },
    { name: "maximize-square-2", label: "Maximize square 2", category: "Arrows Action" },
    { name: "maximize-square-3", label: "Maximize square 3", category: "Arrows Action" },
    { name: "maximize-square-minimalistic", label: "Maximize square minimalistic", category: "Arrows Action" },
    { name: "medal-ribbon", label: "Medal ribbon", category: "Like" },
    { name: "medal-ribbon-star", label: "Medal ribbon star", category: "Like" },
    { name: "medal-ribbons-star", label: "Medal ribbons star", category: "Like" },
    { name: "medal-star", label: "Medal star", category: "Like" },
    { name: "medal-star-circle", label: "Medal star circle", category: "Like" },
    { name: "medal-star-square", label: "Medal star square", category: "Like" },
    { name: "medical-kit", label: "Medical kit", category: "Medicine" },
    { name: "meditation", label: "Meditation", category: "Sports" },
    { name: "meditation-round", label: "Meditation round", category: "Sports" },
    { name: "men", label: "Men", category: "Astronomy" },
    { name: "mention-circle", label: "Mention circle", category: "UI" },
    { name: "mention-square", label: "Mention square", category: "UI" },
    { name: "menu-dots", label: "Menu dots", category: "UI" },
    { name: "menu-dots-circle", label: "Menu dots circle", category: "UI" },
    { name: "menu-dots-square", label: "Menu dots square", category: "UI" },
    { name: "microphone", label: "Microphone", category: "Video" },
    { name: "microphone-2", label: "Microphone 2", category: "Video" },
    { name: "microphone-3", label: "Microphone 3", category: "Video" },
    { name: "microphone-large", label: "Microphone large", category: "Video" },
    { name: "minimalistic-magnifier", label: "Minimalistic magnifier", category: "Search" },
    { name: "minimalistic-magnifier-bug", label: "Minimalistic magnifier bug", category: "Search" },
    { name: "minimalistic-magnifier-zoom-in", label: "Minimalistic magnifier zoom in", category: "Search" },
    { name: "minimalistic-magnifier-zoom-out", label: "Minimalistic magnifier zoom out", category: "Search" },
    { name: "minimize", label: "Minimize", category: "Arrows Action" },
    { name: "minimize-square", label: "Minimize square", category: "Arrows Action" },
    { name: "minimize-square-2", label: "Minimize square 2", category: "Arrows Action" },
    { name: "minimize-square-3", label: "Minimize square 3", category: "Arrows Action" },
    { name: "minimize-square-minimalistic", label: "Minimize square minimalistic", category: "Arrows Action" },
    { name: "minus-circle", label: "Minus circle", category: "UI" },
    { name: "minus-square", label: "Minus square", category: "UI" },
    { name: "mirror", label: "Mirror", category: "Home" },
    { name: "mirror-2", label: "Mirror 2", category: "UI" },
    { name: "mirror-left", label: "Mirror left", category: "Tools" },
    { name: "mirror-right", label: "Mirror right", category: "Tools" },
    { name: "money-bag", label: "Money bag", category: "Money" },
    { name: "money-roll", label: "Money roll", category: "Money" },
    { name: "monitor", label: "Monitor", category: "Devices" },
    { name: "monitor-camera", label: "Monitor camera", category: "Devices" },
    { name: "monitor-smartphone", label: "Monitor smartphone", category: "Devices" },
    { name: "moon", label: "Moon", category: "Weather" },
    { name: "moon-fog", label: "Moon fog", category: "Weather" },
    { name: "moon-sleep", label: "Moon sleep", category: "Weather" },
    { name: "moon-stars", label: "Moon stars", category: "Weather" },
    { name: "mouse", label: "Mouse", category: "Devices" },
    { name: "mouse-circle", label: "Mouse circle", category: "Devices" },
    { name: "mouse-minimalistic", label: "Mouse minimalistic", category: "Devices" },
    { name: "move-to-folder", label: "Move to folder", category: "Folders" },
    { name: "mug", label: "Mug", category: "Food" },
    { name: "multiple-forward-left", label: "Multiple forward left", category: "Messages" },
    { name: "multiple-forward-right", label: "Multiple forward right", category: "Messages" },
    { name: "music-library", label: "Music library", category: "Video" },
    { name: "music-library-2", label: "Music library 2", category: "Video" },
    { name: "music-note", label: "Music note", category: "Video" },
    { name: "music-note-2", label: "Music note 2", category: "Video" },
    { name: "music-note-3", label: "Music note 3", category: "Video" },
    { name: "music-note-4", label: "Music note 4", category: "Video" },
    { name: "music-note-slider", label: "Music note slider", category: "Video" },
    { name: "music-note-slider-2", label: "Music note slider 2", category: "Video" },
    { name: "music-notes", label: "Music notes", category: "Video" },
    { name: "muted", label: "Muted", category: "Video" },
    { name: "notebook", label: "Notebook", category: "Notes" },
    { name: "notebook-2", label: "Notebook 2", category: "School" },
    { name: "notebook-bookmark", label: "Notebook bookmark", category: "School" },
    { name: "notebook-minimalistic", label: "Notebook minimalistic", category: "School" },
    { name: "notebook-square", label: "Notebook square", category: "School" },
    { name: "notes", label: "Notes", category: "Notes" },
    { name: "notes-minimalistic", label: "Notes minimalistic", category: "Notes" },
    { name: "notification-lines-remove", label: "Notification lines remove", category: "Notifications" },
    { name: "notification-remove", label: "Notification remove", category: "Notifications" },
    { name: "notification-unread", label: "Notification unread", category: "Notifications" },
    { name: "notification-unread-lines", label: "Notification unread lines", category: "Notifications" },
    { name: "object-scan", label: "Object scan", category: "Security" },
    { name: "outgoing-call", label: "Outgoing call", category: "Call" },
    { name: "outgoing-call-rounded", label: "Outgoing call rounded", category: "Call" },
    { name: "oven-mitts", label: "Oven mitts", category: "Food" },
    { name: "oven-mitts-minimalistic", label: "Oven mitts minimalistic", category: "Food" },
    { name: "paint-roller", label: "Paint roller", category: "Tools" },
    { name: "palette", label: "Palette", category: "Tools" },
    { name: "palette-2", label: "Palette 2", category: "Tools" },
    { name: "palette-round", label: "Palette round", category: "Tools" },
    { name: "panorama", label: "Panorama", category: "Video" },
    { name: "paper-bin", label: "Paper bin", category: "UI" },
    { name: "paperclip", label: "Paperclip", category: "Messages" },
    { name: "paperclip-2", label: "Paperclip 2", category: "Messages" },
    { name: "paperclip-rounded", label: "Paperclip rounded", category: "Messages" },
    { name: "paperclip-rounded-2", label: "Paperclip rounded 2", category: "Messages" },
    { name: "paragraph-spacing", label: "Paragraph spacing", category: "Text Formatting" },
    { name: "passport", label: "Passport", category: "School" },
    { name: "passport-minimalistic", label: "Passport minimalistic", category: "School" },
    { name: "password", label: "Password", category: "Security" },
    { name: "password-minimalistic", label: "Password minimalistic", category: "Security" },
    { name: "password-minimalistic-input", label: "Password minimalistic input", category: "Security" },
    { name: "pause", label: "Pause", category: "Video" },
    { name: "pause-circle", label: "Pause circle", category: "Video" },
    { name: "paw", label: "Paw", category: "UI" },
    { name: "pen", label: "Pen", category: "Messages" },
    { name: "pen-2", label: "Pen 2", category: "Messages" },
    { name: "pen-new-round", label: "Pen new round", category: "Messages" },
    { name: "pen-new-square", label: "Pen new square", category: "Messages" },
    { name: "people-nearby", label: "People nearby", category: "Map" },
    { name: "perfume", label: "Perfume", category: "UI" },
    { name: "phone", label: "Phone", category: "Call" },
    { name: "phone-calling", label: "Phone calling", category: "Call" },
    { name: "phone-calling-rounded", label: "Phone calling rounded", category: "Call" },
    { name: "phone-rounded", label: "Phone rounded", category: "Call" },
    { name: "pie-chart", label: "Pie chart", category: "Business" },
    { name: "pie-chart-2", label: "Pie chart 2", category: "Business" },
    { name: "pie-chart-3", label: "Pie chart 3", category: "Business" },
    { name: "pill", label: "Pill", category: "Medicine" },
    { name: "pills", label: "Pills", category: "Medicine" },
    { name: "pills-2", label: "Pills 2", category: "Medicine" },
    { name: "pills-3", label: "Pills 3", category: "Medicine" },
    { name: "pin", label: "Pin", category: "UI" },
    { name: "pin-circle", label: "Pin circle", category: "UI" },
    { name: "pin-list", label: "Pin list", category: "UI" },
    { name: "pip", label: "Pip", category: "Video" },
    { name: "pip-2", label: "Pip 2", category: "Video" },
    { name: "pipette", label: "Pipette", category: "Tools" },
    { name: "plane", label: "Plane", category: "Messages" },
    { name: "plane-2", label: "Plane 2", category: "Messages" },
    { name: "plane-3", label: "Plane 3", category: "Messages" },
    { name: "planet", label: "Planet", category: "Astronomy" },
    { name: "planet-2", label: "Planet 2", category: "Astronomy" },
    { name: "planet-3", label: "Planet 3", category: "Astronomy" },
    { name: "planet-4", label: "Planet 4", category: "Astronomy" },
    { name: "plate", label: "Plate", category: "UI" },
    { name: "play", label: "Play", category: "Video" },
    { name: "play-circle", label: "Play circle", category: "Video" },
    { name: "play-stream", label: "Play stream", category: "Video" },
    { name: "playback-speed", label: "Playback speed", category: "Video" },
    { name: "playlist", label: "Playlist", category: "List" },
    { name: "playlist-2", label: "Playlist 2", category: "List" },
    { name: "playlist-minimalistic", label: "Playlist minimalistic", category: "List" },
    { name: "playlist-minimalistic-2", label: "Playlist minimalistic 2", category: "List" },
    { name: "playlist-minimalistic-3", label: "Playlist minimalistic 3", category: "List" },
    { name: "plug-circle", label: "Plug circle", category: "Devices" },
    { name: "plus-minus", label: "Plus minus", category: "School" },
    { name: "podcast", label: "Podcast", category: "Video" },
    { name: "point-on-map", label: "Point on map", category: "Map" },
    { name: "point-on-map-perspective", label: "Point on map perspective", category: "Map" },
    { name: "posts-carousel-horizontal", label: "Posts carousel horizontal", category: "UI" },
    { name: "posts-carousel-vertical", label: "Posts carousel vertical", category: "UI" },
    { name: "power", label: "Power", category: "UI" },
    { name: "presentation-graph", label: "Presentation graph", category: "Business" },
    { name: "printer", label: "Printer", category: "Devices" },
    { name: "printer-2", label: "Printer 2", category: "Devices" },
    { name: "printer-minimalistic", label: "Printer minimalistic", category: "Devices" },
    { name: "programming", label: "Programming", category: "IT" },
    { name: "projector", label: "Projector", category: "Devices" },
    { name: "pulse", label: "Pulse", category: "Medicine" },
    { name: "pulse-2", label: "Pulse 2", category: "Medicine" },
    { name: "qr-code", label: "Qr code", category: "Security" },
    { name: "question-circle", label: "Question circle", category: "UI" },
    { name: "question-square", label: "Question square", category: "UI" },
    { name: "quit-full-screen", label: "Quit full screen", category: "Video" },
    { name: "quit-full-screen-circle", label: "Quit full screen circle", category: "Video" },
    { name: "quit-full-screen-square", label: "Quit full screen square", category: "Video" },
    { name: "quit-pip", label: "Quit pip", category: "Video" },
    { name: "radar", label: "Radar", category: "Map" },
    { name: "radar-2", label: "Radar 2", category: "Map" },
    { name: "radial-blur", label: "Radial blur", category: "Tools" },
    { name: "radio", label: "Radio", category: "Devices" },
    { name: "radio-minimalistic", label: "Radio minimalistic", category: "Devices" },
    { name: "ranking", label: "Ranking", category: "Sports" },
    { name: "receive-square", label: "Receive square", category: "Arrows Action" },
    { name: "receive-twice-square", label: "Receive twice square", category: "Arrows Action" },
    { name: "record", label: "Record", category: "Video" },
    { name: "record-audio-circle", label: "Record audio circle", category: "Video" },
    { name: "record-circle", label: "Record circle", category: "Call" },
    { name: "record-minimalistic", label: "Record minimalistic", category: "Call" },
    { name: "record-square", label: "Record square", category: "Call" },
    { name: "reel", label: "Reel", category: "Video" },
    { name: "reel-2", label: "Reel 2", category: "Video" },
    { name: "refresh", label: "Refresh", category: "Arrows" },
    { name: "refresh-circle", label: "Refresh circle", category: "Arrows" },
    { name: "refresh-square", label: "Refresh square", category: "Arrows" },
    { name: "remote-controller", label: "Remote controller", category: "Home" },
    { name: "remote-controller-2", label: "Remote controller 2", category: "Home" },
    { name: "remote-controller-minimalistic", label: "Remote controller minimalistic", category: "Home" },
    { name: "remove-folder", label: "Remove folder", category: "Folders" },
    { name: "reorder", label: "Reorder", category: "UI" },
    { name: "reorder-2", label: "Reorder 2", category: "Arrows Action" },
    { name: "repeat", label: "Repeat", category: "Video" },
    { name: "repeat-one", label: "Repeat one", category: "Video" },
    { name: "repeat-one-minimalistic", label: "Repeat one minimalistic", category: "Video" },
    { name: "reply", label: "Reply", category: "Arrows Action" },
    { name: "reply-2", label: "Reply 2", category: "Arrows Action" },
    { name: "restart", label: "Restart", category: "Arrows" },
    { name: "restart-circle", label: "Restart circle", category: "Arrows" },
    { name: "restart-square", label: "Restart square", category: "Arrows" },
    { name: "revote", label: "Revote", category: "UI" },
    { name: "rewind-10-seconds-back", label: "Rewind 10 seconds back", category: "Video" },
    { name: "rewind-10-seconds-forward", label: "Rewind 10 seconds forward", category: "Video" },
    { name: "rewind-15-seconds-back", label: "Rewind 15 seconds back", category: "Video" },
    { name: "rewind-15-seconds-forward", label: "Rewind 15 seconds forward", category: "Video" },
    { name: "rewind-5-seconds-back", label: "Rewind 5 seconds back", category: "Video" },
    { name: "rewind-5-seconds-forward", label: "Rewind 5 seconds forward", category: "Video" },
    { name: "rewind-back", label: "Rewind back", category: "Video" },
    { name: "rewind-back-circle", label: "Rewind back circle", category: "Video" },
    { name: "rewind-forward", label: "Rewind forward", category: "Video" },
    { name: "rewind-forward-circle", label: "Rewind forward circle", category: "Video" },
    { name: "rocket", label: "Rocket", category: "Astronomy" },
    { name: "rocket-2", label: "Rocket 2", category: "Astronomy" },
    { name: "rolling-pin", label: "Rolling pin", category: "Food" },
    { name: "round-alt-arrow-down", label: "Round alt arrow down", category: "Arrows" },
    { name: "round-alt-arrow-left", label: "Round alt arrow left", category: "Arrows" },
    { name: "round-alt-arrow-right", label: "Round alt arrow right", category: "Arrows" },
    { name: "round-alt-arrow-up", label: "Round alt arrow up", category: "Arrows" },
    { name: "round-arrow-down", label: "Round arrow down", category: "Arrows" },
    { name: "round-arrow-left", label: "Round arrow left", category: "Arrows" },
    { name: "round-arrow-left-down", label: "Round arrow left down", category: "Arrows" },
    { name: "round-arrow-left-up", label: "Round arrow left up", category: "Arrows" },
    { name: "round-arrow-right", label: "Round arrow right", category: "Arrows" },
    { name: "round-arrow-right-down", label: "Round arrow right down", category: "Arrows" },
    { name: "round-arrow-right-up", label: "Round arrow right up", category: "Arrows" },
    { name: "round-arrow-up", label: "Round arrow up", category: "Arrows" },
    { name: "round-double-alt-arrow-down", label: "Round double alt arrow down", category: "Arrows" },
    { name: "round-double-alt-arrow-left", label: "Round double alt arrow left", category: "Arrows" },
    { name: "round-double-alt-arrow-right", label: "Round double alt arrow right", category: "Arrows" },
    { name: "round-double-alt-arrow-up", label: "Round double alt arrow up", category: "Arrows" },
    { name: "round-graph", label: "Round graph", category: "Business" },
    { name: "round-sort-horizontal", label: "Round sort horizontal", category: "Arrows" },
    { name: "round-sort-vertical", label: "Round sort vertical", category: "Arrows" },
    { name: "round-transfer-diagonal", label: "Round transfer diagonal", category: "Arrows" },
    { name: "round-transfer-horizontal", label: "Round transfer horizontal", category: "Arrows" },
    { name: "round-transfer-vertical", label: "Round transfer vertical", category: "Arrows" },
    { name: "rounded-magnifier", label: "Rounded magnifier", category: "Search" },
    { name: "rounded-magnifier-bug", label: "Rounded magnifier bug", category: "Search" },
    { name: "rounded-magnifier-zoom-in", label: "Rounded magnifier zoom in", category: "Search" },
    { name: "rounded-magnifier-zoom-out", label: "Rounded magnifier zoom out", category: "Search" },
    { name: "route", label: "Route", category: "Map" },
    { name: "routing", label: "Routing", category: "Map" },
    { name: "routing-2", label: "Routing 2", category: "Map" },
    { name: "routing-3", label: "Routing 3", category: "Map" },
    { name: "ruble", label: "Ruble", category: "Money" },
    { name: "rugby", label: "Rugby", category: "Sports" },
    { name: "ruler", label: "Ruler", category: "Tools" },
    { name: "ruler-angular", label: "Ruler angular", category: "Tools" },
    { name: "ruler-cross-pen", label: "Ruler cross pen", category: "Tools" },
    { name: "ruler-pen", label: "Ruler pen", category: "Tools" },
    { name: "running", label: "Running", category: "Sports" },
    { name: "running-2", label: "Running 2", category: "Sports" },
    { name: "running-round", label: "Running round", category: "Sports" },
    { name: "sad-circle", label: "Sad circle", category: "Faces" },
    { name: "sad-square", label: "Sad square", category: "Faces" },
    { name: "safe-2", label: "Safe 2", category: "Money" },
    { name: "safe-circle", label: "Safe circle", category: "Money" },
    { name: "safe-square", label: "Safe square", category: "Money" },
    { name: "sale", label: "Sale", category: "Money" },
    { name: "sale-square", label: "Sale square", category: "Money" },
    { name: "satellite", label: "Satellite", category: "Astronomy" },
    { name: "scale", label: "Scale", category: "Devices" },
    { name: "scaling", label: "Scaling", category: "Arrows Action" },
    { name: "scanner", label: "Scanner", category: "Security" },
    { name: "scanner-2", label: "Scanner 2", category: "Security" },
    { name: "scissors", label: "Scissors", category: "UI" },
    { name: "scissors-square", label: "Scissors square", category: "UI" },
    { name: "scooter", label: "Scooter", category: "Parts" },
    { name: "screen-share", label: "Screen share", category: "Arrows Action" },
    { name: "screencast", label: "Screencast", category: "IT" },
    { name: "screencast-2", label: "Screencast 2", category: "IT" },
    { name: "sd-card", label: "Sd card", category: "Devices" },
    { name: "send-square", label: "Send square", category: "Arrows Action" },
    { name: "send-twice-square", label: "Send twice square", category: "Arrows Action" },
    { name: "server", label: "Server", category: "Devices" },
    { name: "server-2", label: "Server 2", category: "Devices" },
    { name: "server-minimalistic", label: "Server minimalistic", category: "Devices" },
    { name: "server-path", label: "Server path", category: "Devices" },
    { name: "server-square", label: "Server square", category: "Devices" },
    { name: "server-square-cloud", label: "Server square cloud", category: "Devices" },
    { name: "server-square-update", label: "Server square update", category: "Devices" },
    { name: "settings", label: "Settings", category: "Settings" },
    { name: "settings-minimalistic", label: "Settings minimalistic", category: "Settings" },
    { name: "share", label: "Share", category: "UI" },
    { name: "share-circle", label: "Share circle", category: "UI" },
    { name: "shield", label: "Shield", category: "Security" },
    { name: "shield-check", label: "Shield check", category: "Security" },
    { name: "shield-cross", label: "Shield cross", category: "Security" },
    { name: "shield-keyhole", label: "Shield keyhole", category: "Security" },
    { name: "shield-keyhole-minimalistic", label: "Shield keyhole minimalistic", category: "Security" },
    { name: "shield-minimalistic", label: "Shield minimalistic", category: "Security" },
    { name: "shield-minus", label: "Shield minus", category: "Security" },
    { name: "shield-network", label: "Shield network", category: "Security" },
    { name: "shield-plus", label: "Shield plus", category: "Security" },
    { name: "shield-star", label: "Shield star", category: "Security" },
    { name: "shield-up", label: "Shield up", category: "Security" },
    { name: "shield-user", label: "Shield user", category: "Security" },
    { name: "shield-warning", label: "Shield warning", category: "Security" },
    { name: "shock-absorber", label: "Shock absorber", category: "Parts" },
    { name: "shop", label: "Shop", category: "Shopping" },
    { name: "shop-2", label: "Shop 2", category: "Shopping" },
    { name: "shop-minimalistic", label: "Shop minimalistic", category: "Shopping" },
    { name: "shuffle", label: "Shuffle", category: "Video" },
    { name: "sidebar", label: "Sidebar", category: "IT" },
    { name: "sidebar-code", label: "Sidebar code", category: "IT" },
    { name: "sidebar-minimalistic", label: "Sidebar minimalistic", category: "IT" },
    { name: "signpost", label: "Signpost", category: "Map" },
    { name: "signpost-2", label: "Signpost 2", category: "Map" },
    { name: "sim-card", label: "Sim card", category: "Devices" },
    { name: "sim-card-minimalistic", label: "Sim card minimalistic", category: "Devices" },
    { name: "sim-cards", label: "Sim cards", category: "Devices" },
    { name: "siren", label: "Siren", category: "Security" },
    { name: "siren-rounded", label: "Siren rounded", category: "Security" },
    { name: "skateboard", label: "Skateboard", category: "Sports" },
    { name: "skateboarding", label: "Skateboarding", category: "Sports" },
    { name: "skateboarding-round", label: "Skateboarding round", category: "Sports" },
    { name: "skip-next", label: "Skip next", category: "Video" },
    { name: "skip-previous", label: "Skip previous", category: "Video" },
    { name: "skirt", label: "Skirt", category: "UI" },
    { name: "slash-circle", label: "Slash circle", category: "IT" },
    { name: "slash-square", label: "Slash square", category: "IT" },
    { name: "sledgehammer", label: "Sledgehammer", category: "UI" },
    { name: "sleeping", label: "Sleeping", category: "UI" },
    { name: "sleeping-circle", label: "Sleeping circle", category: "Faces" },
    { name: "sleeping-square", label: "Sleeping square", category: "Faces" },
    { name: "slider-horizontal", label: "Slider horizontal", category: "UI" },
    { name: "slider-minimalistic-horizontal", label: "Slider minimalistic horizontal", category: "UI" },
    { name: "slider-vertical", label: "Slider vertical", category: "UI" },
    { name: "slider-vertical-minimalistic", label: "Slider vertical minimalistic", category: "UI" },
    { name: "smart-home", label: "Smart home", category: "UI" },
    { name: "smart-home-angle", label: "Smart home angle", category: "UI" },
    { name: "smart-speaker", label: "Smart speaker", category: "Devices" },
    { name: "smart-speaker-2", label: "Smart speaker 2", category: "Devices" },
    { name: "smart-speaker-minimalistic", label: "Smart speaker minimalistic", category: "Devices" },
    { name: "smart-vacuum-cleaner", label: "Smart vacuum cleaner", category: "Home" },
    { name: "smart-vacuum-cleaner-2", label: "Smart vacuum cleaner 2", category: "Home" },
    { name: "smartphone", label: "Smartphone", category: "Devices" },
    { name: "smartphone-2", label: "Smartphone 2", category: "Devices" },
    { name: "smartphone-rotate-2", label: "Smartphone rotate 2", category: "Devices" },
    { name: "smartphone-rotate-angle", label: "Smartphone rotate angle", category: "Devices" },
    { name: "smartphone-rotate-orientation", label: "Smartphone rotate orientation", category: "Devices" },
    { name: "smartphone-update", label: "Smartphone update", category: "Devices" },
    { name: "smartphone-vibration", label: "Smartphone vibration", category: "Devices" },
    { name: "smile-circle", label: "Smile circle", category: "Faces" },
    { name: "smile-square", label: "Smile square", category: "Faces" },
    { name: "snowflake", label: "Snowflake", category: "Weather" },
    { name: "socket", label: "Socket", category: "Devices" },
    { name: "sofa", label: "Sofa", category: "Home" },
    { name: "sofa-2", label: "Sofa 2", category: "Home" },
    { name: "sofa-3", label: "Sofa 3", category: "Home" },
    { name: "sort", label: "Sort", category: "UI" },
    { name: "sort-alphabetically", label: "Sort alphabetically", category: "List" },
    { name: "sort-by-time", label: "Sort by time", category: "List" },
    { name: "sort-from-bottom-to-top", label: "Sort from bottom to top", category: "List" },
    { name: "sort-from-top-to-bottom", label: "Sort from top to bottom", category: "List" },
    { name: "sort-horizontal", label: "Sort horizontal", category: "Arrows" },
    { name: "sort-vertical", label: "Sort vertical", category: "Arrows" },
    { name: "soundwave", label: "Soundwave", category: "Video" },
    { name: "soundwave-circle", label: "Soundwave circle", category: "Video" },
    { name: "soundwave-square", label: "Soundwave square", category: "Video" },
    { name: "speaker", label: "Speaker", category: "Home" },
    { name: "speaker-minimalistic", label: "Speaker minimalistic", category: "Home" },
    { name: "special-effects", label: "Special effects", category: "UI" },
    { name: "speedometer-low", label: "Speedometer low", category: "Parts" },
    { name: "speedometer-max", label: "Speedometer max", category: "Parts" },
    { name: "speedometer-middle", label: "Speedometer middle", category: "Parts" },
    { name: "square-academic-cap", label: "Square academic cap", category: "School" },
    { name: "square-academic-cap-2", label: "Square academic cap 2", category: "School" },
    { name: "square-alt-arrow-down", label: "Square alt arrow down", category: "Arrows" },
    { name: "square-alt-arrow-left", label: "Square alt arrow left", category: "Arrows" },
    { name: "square-alt-arrow-right", label: "Square alt arrow right", category: "Arrows" },
    { name: "square-alt-arrow-up", label: "Square alt arrow up", category: "Arrows" },
    { name: "square-arrow-down", label: "Square arrow down", category: "Arrows" },
    { name: "square-arrow-left", label: "Square arrow left", category: "Arrows" },
    { name: "square-arrow-left-down", label: "Square arrow left down", category: "Arrows" },
    { name: "square-arrow-left-up", label: "Square arrow left up", category: "Arrows" },
    { name: "square-arrow-right", label: "Square arrow right", category: "Arrows" },
    { name: "square-arrow-right-down", label: "Square arrow right down", category: "Arrows" },
    { name: "square-arrow-right-up", label: "Square arrow right up", category: "Arrows" },
    { name: "square-arrow-up", label: "Square arrow up", category: "Arrows" },
    { name: "square-bottom-down", label: "Square bottom down", category: "Arrows Action" },
    { name: "square-bottom-up", label: "Square bottom up", category: "Arrows Action" },
    { name: "square-double-alt-arrow-down", label: "Square double alt arrow down", category: "Arrows" },
    { name: "square-double-alt-arrow-left", label: "Square double alt arrow left", category: "Arrows" },
    { name: "square-double-alt-arrow-right", label: "Square double alt arrow right", category: "Arrows" },
    { name: "square-double-alt-arrow-up", label: "Square double alt arrow up", category: "Arrows" },
    { name: "square-forward", label: "Square forward", category: "Messages" },
    { name: "square-share-line", label: "Square share line", category: "Messages" },
    { name: "square-sort-horizontal", label: "Square sort horizontal", category: "Arrows" },
    { name: "square-sort-vertical", label: "Square sort vertical", category: "Arrows" },
    { name: "square-top-down", label: "Square top down", category: "Arrows Action" },
    { name: "square-top-up", label: "Square top up", category: "Arrows Action" },
    { name: "square-transfer-horizontal", label: "Square transfer horizontal", category: "Arrows" },
    { name: "square-transfer-vertical", label: "Square transfer vertical", category: "Arrows" },
    { name: "ssd-round", label: "Ssd round", category: "Devices" },
    { name: "ssd-square", label: "Ssd square", category: "Devices" },
    { name: "star", label: "Star", category: "Like" },
    { name: "star-2", label: "Star 2", category: "Astronomy" },
    { name: "star-angle", label: "Star angle", category: "Astronomy" },
    { name: "star-circle", label: "Star circle", category: "Astronomy" },
    { name: "star-fall", label: "Star fall", category: "Astronomy" },
    { name: "star-fall-2", label: "Star fall 2", category: "Astronomy" },
    { name: "star-fall-minimalistic", label: "Star fall minimalistic", category: "Astronomy" },
    { name: "star-fall-minimalistic-2", label: "Star fall minimalistic 2", category: "Astronomy" },
    { name: "star-rainbow", label: "Star rainbow", category: "Astronomy" },
    { name: "star-ring", label: "Star ring", category: "Astronomy" },
    { name: "star-rings", label: "Star rings", category: "Astronomy" },
    { name: "star-shine", label: "Star shine", category: "Like" },
    { name: "stars", label: "Stars", category: "Weather" },
    { name: "stars-2", label: "Stars 2", category: "Astronomy" },
    { name: "stars-line", label: "Stars line", category: "Astronomy" },
    { name: "stars-minimalistic", label: "Stars minimalistic", category: "Astronomy" },
    { name: "station", label: "Station", category: "IT" },
    { name: "station-minimalistic", label: "Station minimalistic", category: "IT" },
    { name: "stethoscope", label: "Stethoscope", category: "Medicine" },
    { name: "sticker-circle", label: "Sticker circle", category: "Faces" },
    { name: "sticker-smile-circle", label: "Sticker smile circle", category: "Faces" },
    { name: "sticker-smile-circle-2", label: "Sticker smile circle 2", category: "Faces" },
    { name: "sticker-smile-square", label: "Sticker smile square", category: "Faces" },
    { name: "sticker-square", label: "Sticker square", category: "Faces" },
    { name: "stop", label: "Stop", category: "Video" },
    { name: "stop-circle", label: "Stop circle", category: "Video" },
    { name: "stopwatch", label: "Stopwatch", category: "Time" },
    { name: "stopwatch-pause", label: "Stopwatch pause", category: "Time" },
    { name: "stopwatch-play", label: "Stopwatch play", category: "Time" },
    { name: "stream", label: "Stream", category: "Video" },
    { name: "streets", label: "Streets", category: "Map" },
    { name: "streets-map-point", label: "Streets map point", category: "Map" },
    { name: "streets-navigation", label: "Streets navigation", category: "Map" },
    { name: "stretching", label: "Stretching", category: "Sports" },
    { name: "stretching-round", label: "Stretching round", category: "Sports" },
    { name: "structure", label: "Structure", category: "IT" },
    { name: "subtitles", label: "Subtitles", category: "UI" },
    { name: "suitcase", label: "Suitcase", category: "Nature" },
    { name: "suitcase-lines", label: "Suitcase lines", category: "Nature" },
    { name: "suitcase-tag", label: "Suitcase tag", category: "Nature" },
    { name: "sun", label: "Sun", category: "Weather" },
    { name: "sun-2", label: "Sun 2", category: "Weather" },
    { name: "sun-fog", label: "Sun fog", category: "Weather" },
    { name: "sunrise", label: "Sunrise", category: "Weather" },
    { name: "sunset", label: "Sunset", category: "Weather" },
    { name: "suspension", label: "Suspension", category: "Parts" },
    { name: "suspension-bolt", label: "Suspension bolt", category: "Parts" },
    { name: "suspension-cross", label: "Suspension cross", category: "Parts" },
    { name: "swimming", label: "Swimming", category: "Sports" },
    { name: "syringe", label: "Syringe", category: "Medicine" },
    { name: "t-shirt", label: "T shirt", category: "UI" },
    { name: "tablet", label: "Tablet", category: "Devices" },
    { name: "tag", label: "Tag", category: "Money" },
    { name: "tag-horizontal", label: "Tag horizontal", category: "Money" },
    { name: "tag-price", label: "Tag price", category: "Money" },
    { name: "target", label: "Target", category: "UI" },
    { name: "tea-cup", label: "Tea cup", category: "Food" },
    { name: "telescope", label: "Telescope", category: "Devices" },
    { name: "temperature", label: "Temperature", category: "Weather" },
    { name: "tennis", label: "Tennis", category: "Sports" },
    { name: "tennis-2", label: "Tennis 2", category: "Sports" },
    { name: "test-tube", label: "Test tube", category: "Medicine" },
    { name: "test-tube-minimalistic", label: "Test tube minimalistic", category: "Medicine" },
    { name: "text-bold", label: "Text bold", category: "Text Formatting" },
    { name: "text-bold-circle", label: "Text bold circle", category: "Text Formatting" },
    { name: "text-bold-square", label: "Text bold square", category: "Text Formatting" },
    { name: "text-circle", label: "Text circle", category: "Text Formatting" },
    { name: "text-cross", label: "Text cross", category: "Text Formatting" },
    { name: "text-cross-circle", label: "Text cross circle", category: "Text Formatting" },
    { name: "text-cross-square", label: "Text cross square", category: "Text Formatting" },
    { name: "text-field", label: "Text field", category: "Text Formatting" },
    { name: "text-field-focus", label: "Text field focus", category: "Text Formatting" },
    { name: "text-format", label: "Text format", category: "Text Formatting" },
    { name: "text-italic", label: "Text italic", category: "Text Formatting" },
    { name: "text-italic-circle", label: "Text italic circle", category: "Text Formatting" },
    { name: "text-italic-square", label: "Text italic square", category: "Text Formatting" },
    { name: "text-selection", label: "Text selection", category: "Text Formatting" },
    { name: "text-square", label: "Text square", category: "Text Formatting" },
    { name: "text-square-2", label: "Text square 2", category: "Text Formatting" },
    { name: "text-underline", label: "Text underline", category: "Text Formatting" },
    { name: "text-underline-circle", label: "Text underline circle", category: "Text Formatting" },
    { name: "text-underline-cross", label: "Text underline cross", category: "Text Formatting" },
    { name: "thermometer", label: "Thermometer", category: "Medicine" },
    { name: "three-squares", label: "Three squares", category: "Tools" },
    { name: "ticker-star", label: "Ticker star", category: "Money" },
    { name: "ticket", label: "Ticket", category: "Money" },
    { name: "ticket-sale", label: "Ticket sale", category: "Money" },
    { name: "to-pip", label: "To pip", category: "Video" },
    { name: "tornado", label: "Tornado", category: "Weather" },
    { name: "tornado-small", label: "Tornado small", category: "Weather" },
    { name: "traffic", label: "Traffic", category: "UI" },
    { name: "traffic-economy", label: "Traffic economy", category: "UI" },
    { name: "tram", label: "Tram", category: "Parts" },
    { name: "transfer-horizontal", label: "Transfer horizontal", category: "Arrows" },
    { name: "transfer-vertical", label: "Transfer vertical", category: "Arrows" },
    { name: "translation", label: "Translation", category: "IT" },
    { name: "translation-2", label: "Translation 2", category: "IT" },
    { name: "transmission", label: "Transmission", category: "Parts" },
    { name: "transmission-circle", label: "Transmission circle", category: "Parts" },
    { name: "transmission-square", label: "Transmission square", category: "Parts" },
    { name: "trash-bin-2", label: "Trash bin 2", category: "UI" },
    { name: "trash-bin-minimalistic", label: "Trash bin minimalistic", category: "UI" },
    { name: "trash-bin-minimalistic-2", label: "Trash bin minimalistic 2", category: "UI" },
    { name: "trash-bin-trash", label: "Trash bin trash", category: "UI" },
    { name: "treadmill", label: "Treadmill", category: "Sports" },
    { name: "treadmill-round", label: "Treadmill round", category: "Sports" },
    { name: "tuning", label: "Tuning", category: "Settings" },
    { name: "tuning-2", label: "Tuning 2", category: "Settings" },
    { name: "tuning-3", label: "Tuning 3", category: "Settings" },
    { name: "tuning-4", label: "Tuning 4", category: "Settings" },
    { name: "tuning-square", label: "Tuning square", category: "Settings" },
    { name: "tuning-square-2", label: "Tuning square 2", category: "Settings" },
    { name: "turntable", label: "Turntable", category: "Devices" },
    { name: "turntable-minimalistic", label: "Turntable minimalistic", category: "Devices" },
    { name: "turntable-music-note", label: "Turntable music note", category: "Devices" },
    { name: "tv", label: "Tv", category: "Devices" },
    { name: "ufo", label: "Ufo", category: "Astronomy" },
    { name: "ufo-2", label: "Ufo 2", category: "Astronomy" },
    { name: "ufo-3", label: "Ufo 3", category: "Astronomy" },
    { name: "umbrella", label: "Umbrella", category: "UI" },
    { name: "undo-left", label: "Undo left", category: "Arrows Action" },
    { name: "undo-left-round", label: "Undo left round", category: "Arrows Action" },
    { name: "undo-left-round-square", label: "Undo left round square", category: "Arrows Action" },
    { name: "undo-left-square", label: "Undo left square", category: "Arrows Action" },
    { name: "undo-right", label: "Undo right", category: "Arrows Action" },
    { name: "undo-right-round", label: "Undo right round", category: "Arrows Action" },
    { name: "undo-right-round-square", label: "Undo right round square", category: "Arrows Action" },
    { name: "undo-right-square", label: "Undo right square", category: "Arrows Action" },
    { name: "unlink", label: "Unlink", category: "Text Formatting" },
    { name: "unlink-minimalistic", label: "Unlink minimalistic", category: "Text Formatting" },
    { name: "unread", label: "Unread", category: "Messages" },
    { name: "upload", label: "Upload", category: "Arrows Action" },
    { name: "upload-minimalistic", label: "Upload minimalistic", category: "Arrows Action" },
    { name: "upload-square", label: "Upload square", category: "Arrows Action" },
    { name: "upload-track", label: "Upload track", category: "Video" },
    { name: "upload-track-2", label: "Upload track 2", category: "Video" },
    { name: "upload-twice-square", label: "Upload twice square", category: "Arrows Action" },
    { name: "usb", label: "Usb", category: "IT" },
    { name: "usb-circle", label: "Usb circle", category: "IT" },
    { name: "usb-square", label: "Usb square", category: "IT" },
    { name: "user", label: "User", category: "Users" },
    { name: "user-block", label: "User block", category: "Users" },
    { name: "user-block-rounded", label: "User block rounded", category: "Users" },
    { name: "user-check", label: "User check", category: "Users" },
    { name: "user-check-rounded", label: "User check rounded", category: "Users" },
    { name: "user-circle", label: "User circle", category: "Users" },
    { name: "user-cross", label: "User cross", category: "Users" },
    { name: "user-cross-rounded", label: "User cross rounded", category: "Users" },
    { name: "user-hand-up", label: "User hand up", category: "Users" },
    { name: "user-hands", label: "User hands", category: "Users" },
    { name: "user-heart", label: "User heart", category: "Users" },
    { name: "user-heart-rounded", label: "User heart rounded", category: "Users" },
    { name: "user-id", label: "User id", category: "Users" },
    { name: "user-minus", label: "User minus", category: "Users" },
    { name: "user-minus-rounded", label: "User minus rounded", category: "Users" },
    { name: "user-plus", label: "User plus", category: "Users" },
    { name: "user-plus-rounded", label: "User plus rounded", category: "Users" },
    { name: "user-rounded", label: "User rounded", category: "Users" },
    { name: "user-speak", label: "User speak", category: "Users" },
    { name: "user-speak-rounded", label: "User speak rounded", category: "Users" },
    { name: "users-group-rounded", label: "Users group rounded", category: "Users" },
    { name: "users-group-two-rounded", label: "Users group two rounded", category: "Users" },
    { name: "vanity", label: "Vanity", category: "Home" },
    { name: "verified-check", label: "Verified check", category: "Money" },
    { name: "video-frame", label: "Video frame", category: "Video" },
    { name: "video-frame-2", label: "Video frame 2", category: "Video" },
    { name: "video-frame-cut", label: "Video frame cut", category: "Video" },
    { name: "video-frame-cut-2", label: "Video frame cut 2", category: "Video" },
    { name: "video-frame-play-horizontal", label: "Video frame play horizontal", category: "Video" },
    { name: "video-frame-play-vertical", label: "Video frame play vertical", category: "Video" },
    { name: "video-frame-replace", label: "Video frame replace", category: "Video" },
    { name: "video-library", label: "Video library", category: "Video" },
    { name: "videocamera", label: "Videocamera", category: "Video" },
    { name: "videocamera-add", label: "Videocamera add", category: "Video" },
    { name: "videocamera-record", label: "Videocamera record", category: "Video" },
    { name: "vinyl", label: "Vinyl", category: "Video" },
    { name: "vinyl-record", label: "Vinyl record", category: "Video" },
    { name: "virus", label: "Virus", category: "Medicine" },
    { name: "volleyball", label: "Volleyball", category: "Sports" },
    { name: "volleyball-2", label: "Volleyball 2", category: "Sports" },
    { name: "volume", label: "Volume", category: "Video" },
    { name: "volume-cross", label: "Volume cross", category: "Video" },
    { name: "volume-knob", label: "Volume knob", category: "Home" },
    { name: "volume-loud", label: "Volume loud", category: "Video" },
    { name: "volume-small", label: "Volume small", category: "Video" },
    { name: "walking", label: "Walking", category: "Sports" },
    { name: "walking-round", label: "Walking round", category: "Sports" },
    { name: "wallet", label: "Wallet", category: "Money" },
    { name: "wallet-2", label: "Wallet 2", category: "Money" },
    { name: "wallet-money", label: "Wallet money", category: "Money" },
    { name: "wallpaper", label: "Wallpaper", category: "Video" },
    { name: "washing-machine", label: "Washing machine", category: "Home" },
    { name: "washing-machine-minimalistic", label: "Washing machine minimalistic", category: "Home" },
    { name: "watch-round", label: "Watch round", category: "Time" },
    { name: "watch-square", label: "Watch square", category: "Time" },
    { name: "watch-square-minimalistic", label: "Watch square minimalistic", category: "Time" },
    { name: "watch-square-minimalistic-charge", label: "Watch square minimalistic charge", category: "Time" },
    { name: "water", label: "Water", category: "Sports" },
    { name: "water-sun", label: "Water sun", category: "Sports" },
    { name: "waterdrop", label: "Waterdrop", category: "UI" },
    { name: "waterdrops", label: "Waterdrops", category: "Weather" },
    { name: "wheel", label: "Wheel", category: "Parts" },
    { name: "wheel-angle", label: "Wheel angle", category: "Parts" },
    { name: "whisk", label: "Whisk", category: "Food" },
    { name: "wi-fi-router", label: "Wi fi router", category: "IT" },
    { name: "wi-fi-router-minimalistic", label: "Wi fi router minimalistic", category: "IT" },
    { name: "wi-fi-router-round", label: "Wi fi router round", category: "IT" },
    { name: "widget", label: "Widget", category: "Settings" },
    { name: "widget-2", label: "Widget 2", category: "Settings" },
    { name: "widget-3", label: "Widget 3", category: "Settings" },
    { name: "widget-4", label: "Widget 4", category: "Settings" },
    { name: "widget-5", label: "Widget 5", category: "Settings" },
    { name: "widget-6", label: "Widget 6", category: "Settings" },
    { name: "widget-add", label: "Widget add", category: "Settings" },
    { name: "win-rar", label: "Win rar", category: "UI" },
    { name: "wind", label: "Wind", category: "Weather" },
    { name: "window-frame", label: "Window frame", category: "IT" },
    { name: "wineglass", label: "Wineglass", category: "Food" },
    { name: "wineglass-triangle", label: "Wineglass triangle", category: "Food" },
    { name: "wireless-charge", label: "Wireless charge", category: "Devices" },
    { name: "women", label: "Women", category: "Astronomy" },
    { name: "xxx", label: "Xxx", category: "UI" },
    { name: "zip-file", label: "Zip file", category: "Files" },
];

export default SOLAR_CATALOG;
